config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  root 'articles#index'

  resources :articles do
    resources :comments
  end

  resources :comments do
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, :as => :commentable, :dependent => :destroy
	validates :title, presence: true,
                    length: { minimum: 5 }
  validates :body, presence: true
  validates :author, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :commentable, :polymorphic => true     
  has_many :comments, :as => :commentable
  def article
  	return @article if defined?(@article)
  	@article = commentable.is_a?(Article) ? commentable : commentable.article
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
  @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
   
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :author)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @parent = Article.find(params[:article_id]) if params[:article_id]   
    @parent = Comment.find(params[:comment_id]) if params[:comment_id]
    @comment = @parent.comments.new(comment_params)
    if @comment.save
      redirect_to article_path(@comment.article)
    else
      render 'new'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.comments.blank?
      @comment.destroy
    end
    redirect_to :back
  end
 
  def new
    @parent = Article.find(params[:article_id]) if params[:article_id]   
    @parent = Comment.find(params[:comment_id]) if params[:comment_id]
    @comment = @parent.comments.build
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :commentable_id, :commentable_type)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for :article, url: articles_path do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        Errors
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :title, class: "col-sm-2 control-label" %><br>
    <%= f.text_field :title, class: "form-control" %>
  </p>
 
  <p>
    <%= f.label :body, class: "col-sm-2 control-label" %><br>
    <%= f.text_area :body, class: "form-control" %>
  </p>
 
	<p>
    <%= f.label :author, class: "col-sm-2 control-label" %><br>
    <%= f.text_field :author, class: "form-control" %>
  </p>

  <p>
    <%= f.submit class: "btn btn-primary btn-sm" %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>

<%= link_to 'Back', articles_path, class: "btn btn-success btn-sm"%>

app/views/articles/index.html.erb
<h1>Magazine</h1>
 
<table class="table table-hover">
  <tr class="active">
    <th>Title</th>
    <th>Body</th>
    <th>Author</th>
    <th colspan="3">Options</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.body %></td>
      <td><%= article.author %></td>
      <td><%= link_to 'Show', article_path(article), class: "btn btn-primary btn-sm" %></td>
      <td><%= link_to 'Edit', edit_article_path(article), class: "btn btn-success btn-sm" %></td>
      <td><%= link_to 'Delete', article_path(article), class: "btn btn-danger btn-sm" ,
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<div align="center">
  <%= link_to 'Create New article', new_article_path, class: "btn btn-primary" %>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>
<%= link_to 'Back', articles_path, class: "btn btn-success btn-sm"%>

app/views/articles/show.html.erb
<h1>Article</h1>
<p></p>
<table class="table table-hover">
  <tr class="info">
  	<th>Title</th>
  	<td><%= @article.title %></td>
  </tr>
  <tr class="active">
  	<th>Body</th>
  	<td><%= @article.body %></td>
  </tr>
  <tr class="warning">
  	<th>Author</th>
  	<td><%= @article.author %></td>
  </tr>
</table>
<%= link_to 'Edit Article', edit_article_path(@article), class: "btn btn-info btn-sm"%>	
<%= link_to 'Back', articles_path, class: "btn btn-success btn-sm"%>
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
<ul class="comment_list">
  <%= render :partial => 'comments/comment', :collection => @article.comments %>
</ul>

app/views/comments/_comment.html.erb
<table class="table table-bordered">
  <tr class="active">
  	<th width="20%">Commenter</th>
  	<td width="50%"><%= comment.commenter%></td>
  </tr>
  <tr class="active">
  	<th>Comment:</th>
  	<td><%= comment.body%></td>
  </tr>
</table>
<p>
	<%= link_to 'Add a Reply', new_comment_comment_path(comment), class: "btn btn-primary btn-sm"%>
  <%= link_to "Delete", article_comment_path(comment.commentable, comment), class: "btn btn-danger btn-sm", :method => :delete, data: { confirm: 'Only comments without replies can be deleted' }%>
</p>
<p>
	<div class="comment"> <%= render :partial => 'comments/comment', :collection => comment.comments %></div>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @comment = Comment.new]) do |f| %>
  <p>
    <%= f.label :commenter, class: "col-sm-2 control-label"%><br>
    <%= f.text_field :commenter, class: "form-control", placeholder: "Commenter"%>
  </p>
  <p>
    <%= f.label :body, class: "col-sm-2 control-label"%><br>
    <%= f.text_area :body, class: "form-control", placeholder: "Body"%>
  </p>
  <p>
    <%= f.submit class: "btn btn-success btn-sm" %>
  </p>
<% end %>

app/views/comments/new.html.erb
<h2>Add a Reply:</h2>
<%= form_for([@parent, @comment = Comment.new]) do |f| %>
  <p>
    <%= f.label :commenter, class: "col-sm-2 control-label"%><br>
    <%= f.text_field :commenter, class: "form-control", placeholder: "Commenter"%>
  </p>
  <p>
    <%= f.label :body, class: "col-sm-2 control-label"%><br>
    <%= f.text_area :body, class: "form-control", placeholder: "Body"%>
  </p>
  <p>
    <%= f.submit class: "btn btn-success btn-sm" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Magazine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Magazine</h1>
<h2> yes <h2>